added search_contact_by_name
LynxUA/yolo-address-book pull request #21
Opened 2024-05-22 16:33 UTC by bodroman

close #4

2024-05-22 22:51 UTC, nrkshaman requested changes

2024-05-22 22:51 UTC, nrkshaman commented on src/handlers.py
> +    return ', '.join(phones)
Коли пофіксиш те що зверху:
Якщо в нас буде збережено
John 1234567890
Jane 0987654321
Користувач напише в консолі:
phone J
Буде вивід
1234567890, 0987654321
Такий вивід не дуже помічний, зручніше напевно буде якшо вивід покаже не тільки список телефонів, а й кому вони належать, якщо контактів в результаті пошуку більше ніж один. Наприклад може бути табличка як в методі all_contacts

2024-05-22 22:51 UTC, nrkshaman commented on src/handlers.py
> +        phones.extend(contact.phones)
1.Код не працює, викидає помилку бо phones це об'єкт Phone, а не стрінга. Потрібно з кожного phone in phones дістати value(яке буде стрінгом)
2. append() i extend() працють по різному, тут треба апенд
https://stackoverflow.com/a/252711

2024-05-22 22:51 UTC, nrkshaman commented on src/models/AddressBook.py
> +    def search_contact_by_name(self, query: str):
якщо тут добавити TypeHints для повернення методу то буде більш наглядно чому в тебе викидає ерору в методі phone_contact. воно достатньо розумне побачити що ти тут повертаєш список, але не достатньо щоб побачити що ти повертаєш список Рекордів
def search_contact_by_name(self, query: str) -> list[Record]:

2024-05-23 10:23 UTC, bodroman commented on src/handlers.py
> +    return ', '.join(phones)
зробив, глянь плз правильність

2024-05-23 15:19 UTC, nrkshaman approved these changes

2024-05-23 16:21 UTC, merged