Task 12
LynxUA/yolo-address-book pull request #28
Opened 2024-05-22 18:57 UTC by Cando1t

Close #12

2024-05-22 23:40 UTC, nrkshaman requested changes

2024-05-22 23:40 UTC, nrkshaman commented on mocker.py
> +            "birthday": fake.date_of_birth(minimum_age=18, maximum_age=90).strftime('%Y-%m-%d')
В нас валідація
`datetime.strptime(value, "%d.%m.%Y")`
перепутав місцями рік і день і через крапку

2024-05-22 23:40 UTC, nrkshaman commented on mocker.py
> +def generate_mock_contacts(num_contacts):
Я б тут зробив функцію методом класу AddressBook(перенести всередину класу)
і наповнював б self обєктами класу Record всередині функції
Або добавити параметр типу AddressBook до цієї функції(тоді функції залишається тут)
тоді не треба створювати/відкривати лишніх файлів і бавитись з джейсоном взагалі

2024-05-22 23:40 UTC, nrkshaman commented on mocker.py
> +def generate_mock_notes(num_notes):
Так само як generate_mock_contacts але для Note i NoteBook

2024-05-22 23:40 UTC, nrkshaman commented on mocker.py
> +    num_contacts = 10
В нас апка використовується введенням input'ів у while True циклі, а не запуском окремих скриптів, тому цей функціонал має викликатися як і весь інший функціонал
Має бути
python main.py
Enter a command: fake 10
[INFO] Book successfully filled with fake data
Можна розбити на дві окремо для нотаток і контактів

2024-05-22 23:43 UTC, nrkshaman requested changes

2024-05-22 23:43 UTC, nrkshaman commented on README.md
> -# yolo-address-book
В цьому PR readme зайвий, бо він вже є в іншому PR і це окрема таска. Але можеш закинути сюда зміни про які я писав в PR по readme і вже хай буде

2024-05-23 17:17 UTC, LynxUA commented on README.md
> -# yolo-address-book
ну взагалі можна змержити той рідмі, і тоді ці зміни не будуть відображатись як зміни.

2024-05-24 14:45 UTC, closed without merging