added method delete
LynxUA/yolo-address-book pull request #33
Opened 2024-05-23 14:17 UTC by bodroman

2024-05-23 14:18 UTC, bodroman commented
close #5

2024-05-23 16:06 UTC, nrkshaman reviewed
Задача полягає трохи в іншому. Цього разу в нас вже є потрібний метод в AddressBook.

Тобі потрібно добавити нову функцію в handlers.py, яка буде мати праметри (*args:list[str], contacts:AddressBook)
Всередині дістати з args name(подивись на сусідні функції)
І потім викликати метод delete - contacts.delete(name)
не забудь поставити відповідний декоратор (@input_error)

Також, тобі потрібно добавити нову команду в main.py(в словнику commands, там де багато lambda) яка буде викликати відповідний hadnler(той який ти добавив в handlers.py)

2024-05-24 09:22 UTC, bodroman commented on src/models/AddressBook.py
> +                          if record.record_name == record_name]
повернув рядок назад.

2024-05-24 09:22 UTC, bodroman commented on src/models/AddressBook.py
> +            del self.data[record_name]
+

2024-05-24 12:49 UTC, nrkshaman requested changes

2024-05-24 12:49 UTC, nrkshaman commented on main.py
видалення `from src.handlers import  *` ламає код і не працює жодна консольна команда

`from src.models.AddressBook import AddressBook`
цей імпорт зайвий, він ніде не використовується

2024-05-24 12:49 UTC, nrkshaman commented on src/handlers.py
> +    contacts.delete(name)
такого методу в AddressBook нема, там є delete_contact.
Поміняй назву в AddressBook на delete

2024-05-24 12:49 UTC, nrkshaman commented on src/models/AddressBook.py
> +    def delete_contact(self, record_name:str) -> None:
поміняти назву delete_contact на delete

2024-05-24 12:55 UTC, bodroman commented on src/handlers.py
> +    contacts.delete(name)
зробив

2024-05-24 12:55 UTC, bodroman commented on src/models/AddressBook.py
> +    def delete_contact(self, record_name:str) -> None:
зробив

2024-05-24 14:09 UTC, nrkshaman approved these changes

2024-05-24 14:10 UTC, merged